apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: franksu1996/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # changes made to these files will get directly updated in pod, if changes
          # made to files outside of this selector, skaffold rebuilds image
          - src: "src/**/*.ts"
            dest: .
